import type { Metadata } from "next";
// import global css
import './globals.css';
import { AppSidebar } from "./components/app-sidebar";
import { Header } from "./components/header";
import { Providers } from "./components/providers"; // gunakan komponen client untuk provider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <AppSidebar />
          <main className="flex flex-1 flex-col overflow-hidden">
            <Header />
            <div className="">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}